#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
	config_load podkop_watchdog
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/podkop-watchdog.sh
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger podkop_watchdog
}
