#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    [ "$(uci -q get podkop_watchdog.main.enabled)" = "1" ] || return 0

    procd_open_instance
    procd_set_param command /bin/sh -c 'sleep 10; exec /usr/libexec/podkop-watchdog.sh'
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "podkop_watchdog"
}
