include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-podkop-watchdog
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=Podkop Watchdog
LUCI_PKGARCH:=all
PKG_MAINTAINER:=oblomo-f

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot
